version: '3.8'

services:
  backend:
    build: .
    container_name: wavy_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/wavy_db
      SECRET_KEY: "потом"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:15
    container_name: wavy_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wavy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: